### ---------------- USUARIOS ----------------
### 1. VER TODOS LOS USUARIOS (GET)
GET http://localhost:8080/api/usuarios

### 2. CREAR UN USUARIO NUEVO (POST)
POST http://localhost:8080/api/usuarios
Content-Type: application/json

{
  "nombre": "Piloto Nuevo",
  "email": "piloto@test.com",
  "password": "123"
}

### 3. ACTUALIZAR UN USUARIO (PUT)
# Nota: Probamos con el ID 2 porque el 1 es el del DataSeeder
PUT http://localhost:8080/api/usuarios/2
Content-Type: application/json

{
  "nombre": "Piloto Actualizado",
  "email": "piloto@test.com"
}

### 4. BORRAR UN USUARIO (DELETE)
DELETE http://localhost:8080/api/usuarios/2

### ---------------- RECURSOS ----------------

### 1. Crear un Recurso (Proyector)
POST http://localhost:8080/api/recursos
Content-Type: application/json

{
  "nombre": "Proyector Epson Sala 1",
  "descripcion": "Proyector 4K HDMI",
  "descripcionAccesible": "Proyector color blanco situado en el techo",
  "codigoQr": "PROY-001",
  "tipo": "EQUIPO_INFORMATICO",
  "estado": "DISPONIBLE"
}

### 2. Listar Recursos (Debería salir el proyector)
GET http://localhost:8080/api/recursos

### 3. Borrar el Recurso (Lógicamente)
DELETE http://localhost:8080/api/recursos/1

### 4. Listar de nuevo (¡Debería salir VACÍA la lista aunque el dato sigue en la BD!)
GET http://localhost:8080/api/recursos

### ---------------- RESERVAS ----------------

### 1. Crear una Reserva
# Asumimos: Usuario ID 1 (Tester) y Recurso ID 1 (El que creaste ayer, si lo borraste crea uno nuevo antes)
POST http://localhost:8080/api/reservas
Content-Type: application/json

{
  "fechaInicio": "2026-02-01T10:00:00",
  "fechaFin": "2026-02-01T12:00:00",
  "usuario": {
    "id": 1
  },
  "recurso": {
    "id": 1
  }
}

### 2. Ver Reservas
GET http://localhost:8080/api/reservas